# Generated by Django 2.2.2 on 2019-06-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_contatomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatomodel',
            name='contato_telefone',
            field=models.CharField(default='', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pessoamodel',
            name='pessoa_logradouro',
            field=models.CharField(default='', max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='pessoamodel',
            name='pessoa_nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoamodel',
            name='pessoa_numero',
            field=models.CharField(default='', max_length=5, verbose_name='Número'),
        ),
    ]
