# Generated by Django 2.2.2 on 2019-06-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20190609_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoamodel',
            name='contato_telefone',
            field=models.CharField(default='', max_length=5, verbose_name='Telefone'),
        ),
    ]
