# Generated by Django 2.2.2 on 2019-06-11 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_pessoamodel_contato_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoModel',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_nome', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contatomodel',
            options={'ordering': ['contato_id'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AddField(
            model_name='pessoamodel',
            name='cidade',
            field=models.CharField(default='', max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='pessoamodel',
            name='estado',
            field=models.CharField(default='', max_length=100, verbose_name='Logradouro'),
        ),
        migrations.CreateModel(
            name='CidadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_id', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.PessoaModel')),
            ],
        ),
    ]
